### ISSUE TITLE
GNOME Initial Setup > Time Zone selection broken without network connection.

### ISSUE THREAD

**Issue by WatchMkr** [system76/gnome-initial-setup#5]

**Comment by jackpot51** [comment]
Fixed in https://github.com/system76/gnome-initial-setup/commit/906c714ea9e1f98459c16418f4c5f7d2c984cb1e, will be available soon.

New ISO spin will have to happen.

**Comment by jackpot51** [comment]
https://launchpad.net/~system76/+archive/ubuntu/pop/+build/13546678
