### ISSUE TITLE
Initial-Setup windows are inconsistent.

### ISSUE THREAD

**Issue by XV-02** [system76/gnome-initial-setup#85]
When going through Gnome-Initial-Setup (GIS), a number of the windows are inconsistently sized or centred. This has been an issue for some time now, and isn't limited to 22.04, though 22.04 was used for screenshots. I've created split-screen comparisons and a reference image:

### Base
"Base" shows the first window of GIS on Pop. Most of the windows are consistent in size and location with this one, including: 
- Welcome to Pop!_OS
- Configure the Top Bar
- Open and Switch Applications from Launcher
- Use Gestures for Easier Navigation
- Appearance
- Network
and
- Privacy

![Base](https://user-images.githubusercontent.com/98765732/162797042-815408e9-4b57-430d-9b55-5d41dea61bdb.png)

### Timezone
The Timezone window is the first incongruous slide in GIS. It is larger, has a different vertical centre, and different top and bottom alignment. The horizontal is consistently centred and the window is equally as wide as the base window. Additionally, once a location is specified for a timezone, the window redraws causing the map and search bar to shift position slightly.

![BaseVsMapClear](https://user-images.githubusercontent.com/98765732/162798442-3a632239-cf7e-4533-a032-f4968d9880bf.png)

![MapClearVsMapSelect](https://user-images.githubusercontent.com/98765732/162798533-cd279ee3-aa01-475d-a781-02be65f5a7ef.png)

### Online Accounts
Online Accounts is different from both the Base window and the Timezone window. Window width and horizontal centring are consistent with Base. The vertical centre and the alignments of neither window bottom and top are not consistent with the Base window.

![BaseVsAccounts](https://user-images.githubusercontent.com/98765732/162799154-b53a1e5a-1166-43a8-951e-f0f291b0da3c.png)

![MapVsAccounts](https://user-images.githubusercontent.com/98765732/162799191-74ea8625-0b84-4457-b8f0-1bdbc6928c6d.png)

**Comment by XV-02** [comment]
### Setup Complete
The Setup Complete window is different from the prior Online Accounts window, and is aligned differently from the Base window vertically - it's vertically centred at the same height as the Online Accounts window - but is the same dimension as the base window.

![AccountsVsComplete](https://user-images.githubusercontent.com/98765732/162800369-5533ae8f-03a9-421e-a165-10b00b29ef8f.png)

![BaseVsAccounts](https://user-images.githubusercontent.com/98765732/162800411-a1ecc5b4-1013-4d62-8414-768a5dd8aa44.png)

[Windows aligned to demonstrate congruence of size.]
![BaseVsCompleteWindowAligned](https://user-images.githubusercontent.com/98765732/162800436-bc316515-a661-411e-a46a-5787e5816c0a.png)

**Comment by n3m0-22** [comment]
Still seeing this on Timezone and Online Accounts.

**Comment by WatchMkr** [comment]
Thanks for putting this bug report together. We're shifting focus to 22.04 bug fixes and COSMIC DE so we won't be working on interface changes unless it's a regression.
